apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydep1
  name: mydep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydep1
    spec:
      containers:
      - image: docker.io/mysql5.6
        name: mysql5-6-p7pkb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: redhat
          - name: MYSQL_DATABASE
            value: database1
        resources: {}
status: {}
